local c = require("SeaShells.colors")

local M = {}

function M.setup()
    local config = require("SeaShells.config")
    local transparent = config.options.transparent
    local p = c.palette
    local bg = transparent and c.misc.none or c.ui.bg0

    return {
        Normal = { fg = c.ui.fg1, bg = bg },
        NormalFloat = { fg = c.ui.fg1, bg = c.ui.bg1 },
        FloatBorder = { fg = c.ui.border, bg = c.ui.bg1 },
        FloatTitle = { fg = p.sunwash, bg = c.ui.bg1, bold = true },
        ColorColumn = { bg = c.ui.bg1 },
        Conceal = { fg = p.mist },
        Cursor = { fg = c.cursor.text, bg = c.cursor.cursor },
        lCursor = { fg = c.cursor.text, bg = c.cursor.cursor },
        CursorColumn = { bg = c.ui.bg1 },
        CursorLine = { bg = c.ui.bg1 },
        CursorLineNr = { fg = p.sunwash, bold = true },
        Directory = { fg = p.sea_glass },
        EndOfBuffer = { fg = c.ui.bg4 },
        ErrorMsg = { fg = p.coral, bold = true },
        FoldColumn = { fg = c.ui.fg3, bg = bg },
        Folded = { fg = p.mist, bg = c.ui.bg1 },
        IncSearch = { fg = c.cursor.text, bg = p.amber },
        LineNr = { fg = c.ui.fg3 },
        MatchParen = { fg = p.shell, bg = p.deep_plum, bold = true },
        ModeMsg = { fg = p.sunwash, bold = true },
        MoreMsg = { fg = p.kelp },
        NonText = { fg = c.ui.bg4 },
        Pmenu = { fg = c.ui.fg1, bg = c.ui.bg1 },
        PmenuSbar = { bg = c.ui.bg2 },
        PmenuSel = { fg = p.shell, bg = p.deep_plum },
        PmenuThumb = { bg = p.slate },
        Question = { fg = p.kelp },
        Search = { fg = c.cursor.text, bg = p.sunwash },
        SignColumn = { fg = c.ui.fg3, bg = bg },
        SpecialKey = { fg = p.slate },
        SpellBad = { sp = p.coral, undercurl = true },
        SpellCap = { sp = p.tide, undercurl = true },
        SpellLocal = { sp = p.sea_glass, undercurl = true },
        SpellRare = { sp = p.foam, undercurl = true },
        StatusLine = { fg = c.ui.fg0, bg = c.ui.bg2 },
        StatusLineNC = { fg = c.ui.fg3, bg = c.ui.bg1 },
        Substitute = { fg = c.cursor.text, bg = p.washed_coral },
        TabLine = { fg = c.ui.fg3, bg = c.ui.bg1 },
        TabLineFill = { bg = c.ui.bg0 },
        TabLineSel = { fg = p.shell, bg = c.ui.bg2, bold = true },
        Title = { fg = p.seafoam, bold = true },
        VertSplit = { fg = c.ui.border },
        Visual = { fg = c.selection.text, bg = c.selection.background },
        WarningMsg = { fg = p.amber },
        WildMenu = { fg = c.cursor.text, bg = p.amber },
        WinSeparator = { fg = c.ui.border },

        Comment = { fg = p.mauve_pearl, italic = true },
        Constant = { fg = p.sunwash },
        String = { fg = p.shell },
        Character = { fg = p.shell },
        Number = { fg = p.surf },
        Boolean = { fg = p.plum_shell },
        Float = { fg = p.sunwash },
        Identifier = { fg = p.surf },
        Function = { fg = p.seafoam },
        Statement = { fg = p.reef_red },
        Conditional = { fg = p.reef_red },
        Repeat = { fg = p.reef_red },
        Label = { fg = p.amber },
        Operator = { fg = p.mist },
        Keyword = { fg = p.reef_red },
        Exception = { fg = p.reef_red },
        PreProc = { fg = p.foam },
        Include = { fg = p.surf },
        Define = { fg = p.foam },
        Macro = { fg = p.foam },
        PreCondit = { fg = p.surf },
        Type = { fg = p.eelgrass },
        StorageClass = { fg = p.reef_red },
        Structure = { fg = p.sea_glass },
        Typedef = { fg = p.sunwash },
        Special = { fg = p.foam },
        SpecialChar = { fg = p.foam },
        Tag = { fg = p.amber },
        Delimiter = { fg = p.driftwood },
        SpecialComment = { fg = p.eelgrass, italic = true },
        Debug = { fg = p.reef_red },
        Underlined = { fg = p.surf, underline = true },
        Ignore = { fg = c.ui.fg3 },
        Error = { fg = p.reef_red, bg = c.diff.delete },
        Todo = { fg = c.cursor.text, bg = p.amber, bold = true },

        DiagnosticError = { fg = p.reef_red },
        DiagnosticWarn = { fg = p.amber },
        DiagnosticInfo = { fg = p.sea_glass },
        DiagnosticHint = { fg = p.eelgrass },
        DiagnosticOk = { fg = p.eelgrass },
        DiagnosticUnderlineError = { sp = p.reef_red, undercurl = true },
        DiagnosticUnderlineWarn = { sp = p.amber, undercurl = true },
        DiagnosticUnderlineInfo = { sp = p.sea_glass, undercurl = true },
        DiagnosticUnderlineHint = { sp = p.eelgrass, undercurl = true },
        DiagnosticUnderlineOk = { sp = p.eelgrass, undercurl = true },

        DiffAdd = { bg = c.diff.add },
        DiffChange = { bg = c.diff.change },
        DiffDelete = { fg = p.reef_red, bg = c.diff.delete },
        DiffText = { bg = c.diff.text },

        GitSignsAdd = { fg = p.eelgrass },
        GitSignsChange = { fg = p.amber },
        GitSignsDelete = { fg = p.reef_red },

        pythonDocString = { fg = p.eelgrass, italic = true },
        pythonDocTest = { fg = p.eelgrass },

        TreesitterContext = { bg = c.ui.bg1 },
        TelescopeBorder = { fg = c.ui.border, bg = c.ui.bg1 },
        TelescopeNormal = { fg = c.ui.fg1, bg = c.ui.bg1 },
        TelescopeSelection = { fg = p.shell, bg = p.deep_plum },
        TelescopeMatching = { fg = p.amber, bold = true },
        CmpItemAbbrMatch = { fg = p.surf, bold = true },
        CmpItemAbbrMatchFuzzy = { fg = p.surf },
        CmpItemKind = { fg = p.foam },

        ["@attribute"] = { fg = p.sunwash },
        ["@boolean"] = { fg = p.plum_shell },
        ["@character"] = { fg = p.shell },
        ["@comment"] = { fg = p.mauve_pearl, italic = true },
        ["@comment.documentation"] = { fg = p.eelgrass, italic = true },
        ["@constant"] = { fg = p.sunwash },
        ["@constructor"] = { fg = p.sea_glass },
        ["@function"] = { fg = p.seafoam },
        ["@function.builtin"] = { fg = p.foam },
        ["@function.call"] = { fg = p.seafoam },
        ["@function.method"] = { fg = p.sea_glass },
        ["@function.method.call"] = { fg = p.sea_glass },
        ["@keyword"] = { fg = p.reef_red },
        ["@keyword.conditional"] = { fg = p.reef_red },
        ["@keyword.exception"] = { fg = p.reef_red },
        ["@keyword.function"] = { fg = p.reef_red },
        ["@keyword.import"] = { fg = p.surf },
        ["@keyword.repeat"] = { fg = p.reef_red },
        ["@module"] = { fg = p.surf },
        ["@number"] = { fg = p.surf },
        ["@number.float"] = { fg = p.sunwash },
        ["@operator"] = { fg = p.mist },
        ["@property"] = { fg = p.sunwash },
        ["@punctuation.bracket"] = { fg = p.driftwood },
        ["@punctuation.delimiter"] = { fg = p.driftwood },
        ["@punctuation.special"] = { fg = p.foam },
        ["@string"] = { fg = p.shell },
        ["@string.documentation"] = { fg = p.eelgrass, italic = true },
        ["@string.escape"] = { fg = p.foam },
        ["@string.regex"] = { fg = p.sunwash },
        ["@tag"] = { fg = p.reef_red },
        ["@tag.attribute"] = { fg = p.sunwash },
        ["@tag.delimiter"] = { fg = p.driftwood },
        ["@type"] = { fg = p.eelgrass },
        ["@type.builtin"] = { fg = p.eelgrass },
        ["@variable"] = { fg = c.ui.fg1 },
        ["@variable.builtin"] = { fg = p.plum_shell },
        ["@variable.member"] = { fg = p.sunwash },
        ["@variable.parameter"] = { fg = p.mist },

        ["@comment.documentation.python"] = { fg = p.eelgrass, italic = true },
        ["@string.documentation.python"] = { fg = p.eelgrass, italic = true },
        ["@type.python"] = { fg = p.eelgrass },
        ["@type.builtin.python"] = { fg = p.eelgrass },
    }
end

return M
